version: '3'
services:
    mysql:
        container_name: mblog-mysql
        image: mysql/mysql-server:5.7
        environment:
            MYSQL_DATABASE: db_mblog
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
            TZ: Asia/Shanghai
        ports:
        - "3306:3306"
        expose:
        - "3306"
        volumes:
        - ./mysql/mysql_data:/var/lib/mysql
        restart: always

    server:
        container_name: mblog
        build: .
        working_dir: /app
        environment:
            TZ: Asia/Shanghai
        volumes:
        - ./:/app
        - ~/.m2:/root/.m2
        - ./logs:/app/logs
        ports:
        - "80:8080"
        #command: mvn clean spring-boot:run -Dspring-boot.run.profiles=mysql -Dmaven.test.skip=true
        depends_on:
        - mysql
        restart: always