spring:
    datasource:
        #schema: classpath*:config/db/db_mblog.sql
        #initialization-mode: always
        #continue-on-error: false
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/db_mblog?useSSL=false&characterEncoding=utf8
        username: root
        password: root

    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.config.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.store.root}/indexes